### ISSUE TITLE
系统语言为英文的情况下，权限名称有中文有英文

### ISSUE THREAD

**Issue by mpco** [8enet/AppOpsX#1]
如题，请修复，感谢开发者。

**Comment by 8enet** [comment]
确实会这样，当时没有考虑太多i18n的情况，最近实在太忙，后期会修复的:smile:

**Comment by MaiTestarossa** [comment]
遇到类似的问题，
- 系统语言为日文安装app后，app内改成中文如下图。
- 系统改回中文后，app内仍然如下图，
不管app内语言切换成何种语言，部分权限文字永远是首次安装时的语言（日语），不会被改变
- 卸载后重新安装解决，可能清除数据也可以解决，不算大问题。

![snipaste_20180201_205817](https://user-images.githubusercontent.com/20226906/35679686-f761d818-0792-11e8-98e7-472fad2b81bb.png)
