### ISSUE TITLE
建议在应用权限界面添加【隐藏无此权限的app】的选项

### ISSUE THREAD

**Issue by bitching** [8enet/AppOpsX#12]
若此界面添加【隐藏无此权限的app】的选项使用起来会方便很多。
毕竟现在很多系统内置组件也是数据收集器，显示系统组件后，将会极大地加长这个列表。。。
![screenshot_20170723-141401](https://user-images.githubusercontent.com/12702029/28497131-ca20ee26-6fb1-11e7-8d89-16eac37828f9.png)

**Comment by 8enet** [comment]
这个分组列表是读取每个应用得到的，没有此权限的也不会显示在这，不太明白你的隐藏是什么意思

**Comment by bitching** [comment]
我用词不太准确，应该是【隐藏已关闭此权限的条目】
大概就是例如下图这样：
![screenshot_20170725-225735](https://user-images.githubusercontent.com/12702029/28579120-4e3f01ba-718e-11e7-8fa2-0ddaa011295d.png)
例如【在其他应用之上显示内容】这个分组里面，只有3个app得到允许，如果有个开关可以隐藏掉其他未得到授权的条目，只显示这3个得到授权的app就好了。
因为有些敏感权限分组或者重灾区，得到授权的app极少（如访问确切位置25/100，读取手机状态和身份45/127等等），有此开关控制显示的内容会有较大帮助。
望采纳。
