### ISSUE TITLE
不支持MagiskSU

### ISSUE THREAD

**Issue by iVanilla** [8enet/AppOpsX#16]
显示连接失败，开启root兼容模式无效。
![](https://i.loli.net/2017/09/13/59b8da2d50e65.png)

设备是红米Note3(代号kenzo)
Android 8.0.0
Magisk是14.0版本

**Comment by runapp** [comment]
1.贴log
2.缩图
3.很可能是8.0的问题，7.1表示没问题。

**Comment by iVanilla** [comment]
@runapp

`SELinux:

Wed Sep 13 20:07:48 GMT+08:00 2017
root start log
Permissive
0
end
 $ id
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0
start
th:52053,token:b953a8c771fec69f2c177635ac5fbadc,bgrun                         <:1   & 
AppOpsMain $@ type:adb,path:52053,token:b953a8c771fec                         <69f2c177635ac5fbadc,bgrun
m.zzzmode.appopsx.server.AppOpsMain $@ type:adb,path:                         <52053,token:b953a8c771fec
pp_process /system/bin com.zzzmode.appopsx.server.App                         <OpsMain $@ type:adb,path:
jar;echo start;id;exec  app_process /system/bin com.z                         <zzmode.appopsx.server.App
popsx/files/opsx/appopsx.jar;echo start;id;exec  app_                         <process /system/bin com.z
droid/data/com.zzzmode.appopsx/files/opsx/appopsx.jar                         <;echo start;id;exec  app_
TH=/storage/emulated/0/Android/data/com.zzzmode.appop                         <sx/files/opsx/appopsx.jar
stem/lib64;export CLASSPATH=/storage/emulated/0/Andro                         <id/data/com.zzzmode.appop
RY_PATH=/vendor/lib64:/system/lib64;export CLASSPATH=                         </storage/emulated/0/Andro
kenzo:/ $ export LD_LIBRARY_PATH=/vendor/lib64:/system/lib64;export CLASSPATH=
uid=2000(shell) gid=2000(shell) groups=2000(shell),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:shell:s0
[1] 3820
kenzo:/ $ CANNOT LINK EXECUTABLE "/system/bin/dex2oat": "/system/lib64/libart.so" is 64-bit instead of 32-bit`

**Comment by runapp** [comment]
这是什么操作……你手动运行了脚本吗

**Comment by iVanilla** [comment]
@runapp 等下，我感觉这在哪里见过你。。。你的telegram username是不是一样的？如果是，我给你发个录屏gif

**Comment by runapp** [comment]
发吧

**Comment by 8enet** [comment]
不用root兼容模式，直接用root可么

**Comment by churchmice** [comment]
感觉我的pixel也有同样的问题，直接卡死

**Comment by iVanilla** [comment]
@8enet 抱歉之前没留意，一直没回复。

在 7.1 测试是没有问题的，所以应该是不兼容 8.0。

因为 OpenGApps 的问题，我已经退回 7.1 了，这群我先加了吧，有问题再通过 telegram 反馈。
