### ISSUE TITLE
 [已解决] adb 模式失败

### ISSUE THREAD

**Issue by hanghang** [8enet/AppOpsX#18]
弄了半天无法成功，是不是漏做了什么步骤。。。

0. 手机：坚果Pro （无法root）Android 7.1    ， 红米Note3 lineageOS 14.1 Android7.1 root模式OK，ADB模式同样结果

1.设置端口
![_screenshot_2017-10-01-11-08-36-441_appopsx](https://user-images.githubusercontent.com/3734451/31051430-a10df080-a62d-11e7-9986-02c92162a6a1.png)

2. 执行adb命令
$ adb tcpip 6666

3.结果失败
![screenshot_2017-10-01-11-21-22-851_appopsx](https://user-images.githubusercontent.com/3734451/31051440-23b8256e-a62e-11e7-838a-fba779ed2a7c.png)

4. $ adb shell sh /sdcard/Android/data/com.zzzmode.appopsx/opsx.sh &
依然无效

5.
[adb.log](https://github.com/8enet/AppOpsX/files/1346899/adb.log)

**Comment by hanghang** [comment]
manifast 里添加
`  <uses-permission android:name="android.permission.INTERNET"/>`
后问题解决了，关了吧  ：）

**Comment by 8enet** [comment]
对，需要网络权限，之前整理的时候错误删除了，非常感谢提醒！
