### ISSUE TITLE
/sdcard/Android/data/com.zzzmode.appopsx/opsx.sh: not found

### ISSUE THREAD

**Issue by choury** [8enet/AppOpsX#29]
是不是这个文件忘记打包了？

**Comment by 8enet** [comment]
安装好先打开应用一次

**Comment by choury** [comment]
试了，一样，清理数据杀掉重进，还是没有

**Comment by 8enet** [comment]
这个目录存在吗

**Comment by choury** [comment]
目录存在，里面有files目录，files目录为空

**Comment by 8enet** [comment]
/sdcard/Android/data/com.zzzmode.appopsx/ 这个目录下也没有文件么

**Comment by choury** [comment]
$ ls /sdcard/Android/data/com.zzzmode.appopsx/ -lha
total 24K
drwxrwx---  3 u0_a130 everybody 4.0K Jan 16 15:58 .
drwxrwx--- 31 root    everybody 4.0K Jan 16 15:58 ..
drwxrwx---  2 u0_a130 everybody 4.0K Jan 16 15:58 files
$

**Comment by 8enet** [comment]
奇怪，可以用logcat抓些日志么，问题应该出现在应用启动的时候:sweat_smile:

**Comment by choury** [comment]
01-16 13:27:04.369  4139  4139 F DEBUG   : Abort message: 'art/runtime/thread.cc:1661] No pending exception expected: java.lang.ClassNotFoundException: Didn't find class "com.zzzmode.appopsx.server.AppOpsMain" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib64, /vendor/lib64, /system/lib64, /vendor/lib64]]'

**Comment by choury** [comment]
01-16 16:11:52.833  1332  2376 I ActivityManager: START u0 {cmp=com.zzzmode.appopsx/.ui.main.SettingsActivity} from uid 10130 on display 0                              01-16 16:12:01.126  1332 17594 I ActivityManager: START u0 {cmp=com.zzzmode.appopsx/.ui.permission.AppPermissionActivity (has extras)} from uid 10130 on display 0      01-16 16:12:01.311  1332  3212 D VoldConnector: SND -> {265 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:07.659  1332  3087 D VoldConnector: SND -> {266 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:10.983  1332  1377 D VoldConnector: SND -> {267 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:15.733  1332  2182 D VoldConnector: SND -> {268 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:18.964  1332 17592 D VoldConnector: SND -> {269 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:22.142  1332  2376 D VoldConnector: SND -> {270 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:27.040  1332  3125 D VoldConnector: SND -> {271 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:30.285  1332 12651 D VoldConnector: SND -> {272 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}                                  01-16 16:12:33.411  1332  5207 D VoldConnector: SND -> {273 volume mkdirs /storage/emulated/0/Android/data/com.zzzmode.appopsx/files/}

**Comment by 8enet** [comment]
请问这是什么设备？能否提供更完整的log啊

**Comment by choury** [comment]
lineageos 14 on OnePlus 5
用的是logcat | grep zzzmode抓出来的，没有其他的了，你用的标签是什么？

**Comment by 8enet** [comment]
看样子那个文件又生成了？grep pid看到的应该多一点

**Comment by choury** [comment]
卸载后重装恢复正常，估计是没获取到读写sd卡的权限
