### ISSUE TITLE
精确位置/允许使用基站的粗略位置/允许应用监听位置数据等几个权限无法关闭

### ISSUE THREAD

**Issue by dubu45** [8enet/AppOpsX#31]
Android 6.0.1
Google Nexus 5

使用时发现，精确位置/允许使用基站的粗略位置/允许应用监听位置数据等几个权限无法关闭，关闭后再点进去，发现权限还是开启状态。

谢谢。

**Comment by zbinlin** [comment]
我的是：

Android 7.1.2 (LineageOS 14.1)
Moto G

的，发现同样存在这个问题。

同时在关闭模板时设置关闭这些权限后，新安装的应用依然会打开这些权限。

PS: 设置关闭权限时，在 `adb logcat` 可以看到这句 log：
> E appopsx : Flog -->  appops Builder{action='set', packageName='ca.cmetcalfe.locationshare', userHandleId=0, opInt=41, modeInt=1}
