### ISSUE TITLE
adb电脑调试出现问题

### ISSUE THREAD

**Issue by bkfrd** [8enet/AppOpsX#8]
AppOpsX 1.1.8
Oppo A37m
Android 5.1 (Color OS 3.0.0)
KingRoot
错误代码：
java.lang.SecurityException: uid 2000 does not have android.permission.GET_APP_OPS_STATS.
另外root模式不稳定，刚开始几次可以成功，后来根本打不开权限列表。卸载重装，root兼容模式都不能解决问题。重新root后解决了问题。不知道还能坚持多久。或许是kingroot的问题。

**Comment by 8enet** [comment]
建议用supersu试试，root模式不可以大多是selinux引起的，关闭selinux可以解决。
root兼容模式只是使用root开启远程adb然后使用adb模式连接的，绕过了selinux规则，避免关闭selinux引起的安全问题。
但是这个错误来看adb shell用户没权限操作，看样子只能root模式了。
