### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by lq19931201** [8enet/AppOpsX#9]
opsxlib里面的build.gradle 第83行报错
paths.add(file.path.replaceFirst(ignorePrefix,""))
请问应该如何解决呢

**Comment by 8enet** [comment]
报什么错呢？

**Comment by lq19931201** [comment]
Error:(83, 1) Execution failed for task ':opsxlib:build'.
> Illegal/unsupported escape sequence near index 3
  C:\Users\admunn\Desktop\AppOps\AppOpsX-master\opsxlib\build/intermediates/classes/debug\
     ^
这个错误 我也不清楚是什么问题，谢啦

**Comment by 8enet** [comment]
win下路径用\，我在代码里写的/:sweat_smile:

**Comment by lq19931201** [comment]
好的
我还有一个关于权限的问题想问
就是我想问一下，如何能够将一些权限设置成允许
这个问题困扰我好几周了
用AppOpsManager么？

**Comment by 8enet** [comment]
建议看Settings源码，里面很多系统api的调用，AppOpsManager只是忽略了一些权限处理

**Comment by lq19931201** [comment]
Error:(83, 1) Execution failed for task ':opsxlib:build'.
> Illegal/unsupported escape sequence near index 3
  C:\Users\admunn\Desktop\AppOps\AppOpsX-master\opsxlib\build\intermediates\classes\debug\
     ^
还是有错误

**Comment by 8enet** [comment]
还是那个错误吗，我明天仔细看看😀

**Comment by lq19931201** [comment]
好的，很感谢你
可以加一下QQ嘛，有不懂的可以问一下你嘛

**Comment by 8enet** [comment]
base64
MTIxMDc3NjMxOA==
